### ISSUE TITLE
Mushroom Media Card

### ISSUE THREAD

**Issue by tonynogs** [excaliburpartners/HAILogger#62]
Not sure if this is the right place to ask the question... but does anyone know of a way to use the Media Card entity to control the audio sources/zones now that HiFi support has been integrated into 1.1.16.2? 

Seems like I would need to be able to convert the switch.omnilink / select.omnilink / number.omnilink to a media.omnilink entity. 

(Let me know if there is a better forum to ask this... since it's not really an "issue" with your product) Thanks!

**Comment by rwagoner** [comment]
Home Assistant doesn't offer a MQTT media player. I would look at the Home Assistant [Universal media player](https://www.home-assistant.io/integrations/universal/), which allows you to combine controls into a media player. Currently OmniLink Bridge exposes MQTT controls for power, volume, mute, and source.

**Comment by tonynogs** [comment]
I've been trying to get that to work, added the following to my configuration.yaml file, but still not seeing anything after a restart. Any ideas?

`media_player:
  - platform: universal
    name: Home_Audio_Kitchen
    commands:
    turn_on:
      service: switch.turn_on
      target:
        entity_id: switch.omnilink_kitchen
    turn_off:
      service: switch.turn_off_kitchen
      target:
        entity_id: switch.omnilink_kitchen
    volume_up:
      service: switch.turn_on_kitchen
      target:
        entity_id: number.omnilink_kitchen_volume
    volume_down:
      service: switch.turn_on_kitchen
      target:
        entity_id: number.omnilink_kitchen_volume
    volume_mute:
      service: switch.turn_on_kitchen
      target:
        entity_id: switch.omnilink_kitchen_mute
    select_source:
      service: media_player.select_source_kitchen
      target:
        entity_id: select.omnilink_kitchen_source
        data:
        source: '{{ source }}'`

**Comment by enry86cami** [comment]
Sorry, but I'm not able to do this,
these are my posts:
https://community.home-assistant.io/t/universal-media-player-problem/724140
https://community.home-assistant.io/t/media-player-template/203062/158
https://github.com/Sennevds/media_player.template/issues/52


Il giorno sab 4 mag 2024 alle ore 23:23 tonynogs ***@***.***>
ha scritto:

**Comment by tonynogs** [comment]
My workaround so far is to use a Tile Card and a Mushroom Select card vertically stacked. Clicking on the top icon turns the zone ON/OFF and clicking the bottom icon MUTES.

![Screenshot 2024-05-04 152952](https://github.com/excaliburpartners/OmniLinkBridge/assets/162737403/94e08dd2-82f5-4799-af38-dafcc493dcb7)

**Comment by rwagoner** [comment]
> Sorry, but I'm not able to do this, these are my posts: 

I don't have any audio zones to test, but did test the following with input helpers. The media player attribute volume_level will not take a template so I have to use a template number to scale 0-100 to 0-1.

```
template:
  number: 
    - name: omnilink_ZONE_volume_scaling
      step: 0.01
      min: 0
      max: 1
      state: > 
          {{ states('number.omnilink_ZONE_volume') | float * 0.01 }}
      set_value:
          service: number.set_value 
          target:
            entity_id: number.omnilink_ZONE_volume
          data:
            value: "{{ value | float * 100 }}"

media_player:
  platform: universal
  name: Audio Zone
  commands:
    turn_on:
      service: switch.turn_on
      target:
        entity_id: switch.omnilink_ZONE
    turn_off:
      service: switch.turn_off
      target:
        entity_id: switch.omnilink_ZONE
    volume_up:
      service: number.set_value
      target:
        entity_id: number.omnilink_ZONE_volume
      data:
        value: "{{ states('number.omnilink_ZONE_volume') | int + 1 }}"
    volume_down:
      service: number.set_value
      target:
        entity_id: number.omnilink_ZONE_volume
      data:
        value: "{{ states('number.omnilink_ZONE_volume') | int - 1 }}"
    volume_mute:
      service: switch.turn_on
      target:
        entity_id: switch.omnilink_ZONE_mute
    select_source:
      service: select.select_option
      target:
        entity_id: select.omnilink_ZONE_source
      data:
        option: "{{ source }}"
    volume_set:
      service: number.set_value 
      target:
        entity_id: number.omnilink_ZONE_volume
      data:
        value: "{{ volume_level | float * 100 }}"

  attributes:
    state: switch.omnilink_ZONE
    is_volume_muted: switch.omnilink_ZONE_mute
    volume_level: number.omnilink_ZONE_volume_scaling
    source: select.omnilink_ZONE_source
    source_list: select.omnilink_ZONE_source|options
```
